version: "1"
rules:                      # Array of rules
  - base: development            # Required. Target branch
    upstream: GeyserMC:development    # Required. Must be in the same fork network.
    mergeMethod: squash  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
  - base: dev
    upstream: development        # Required. Can be a branch in the same forked repo.
label: ":arrow_heading_down: pull"  # Optional
