version: 2 # Use version 2.1 to enable Orb usage.
 
jobs:
  build: 
    working_directory: ~/Floodgate/Floodgate
    parallelism: 1
    shell: /bin/bash --login
    environment:
      TERM: dumb
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      _JAVA_OPTIONS: "-Xmx4g"
    docker:
      - image: circleci/openjdk:8-jdk-stretch # ...with this image as the primary container; this is where all `steps` will run
      - image: circleci/clojure:openjdk-8-tools-deps-stretch
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circle_test
    steps:
    # Machine Setup
    - checkout
    # Prepare for artifact
    - run: mkdir -p %CIRCLE_ARTIFACTS% %CIRCLE_TEST_REPORTS%
    # Dependencies
    - run: sudo apt update
    - run: sudo apt upgrade
    - run: sudo apt-get install maven
    - run: sudo apt-get install openjdk-8-jdk
    - run: sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java; sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac; echo -e "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $BASH_ENV
   # - run: mvn dependency:go-offline
    - run: sudo mvn clean
    # Restore the dependency cache
    - restore_cache:
        keys:
        # This branch if available
        - v1-dep-{{ .Branch }}-
        # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
        - v1-dep-
    - run: export TERM=${TERM:-dumb}
    - run: git config --global user.email "circle@circleci.com"
    - run: git config --global user.name "CircleCI"
    - run: sudo chmod -Rv +x bukkit
    - run: sudo chmod -Rv +x bungee
    - run: sudo chmod -Rv +x common
    - run: sudo chmod -Rv +x velocity
    - run: sudo chmod -Rv +x .circleci/builds.sh
    - run: sudo mvn clean package
    - run: mkdir builds
    #- run: cp -rf ./target/bukkit/*.jar ./builds | cp -rf ./**/target/*.jar ./builds/
    - run: sudo .circleci/builds.sh
    # Save dependency cache
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/.m2
    # Test
    - run: yes|cp -rf ./builds/ $CIRCLE_ARTIFACTS
    # Teardown
    # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results
#    - add_ssh_keys:
#        fingerprints:
#          - "7b:8e:5c:68:31:7b:66:4c:29:20:66:55:9b:c8:b2:d2"  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /tmp/circleci-artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
