name: ${project.name}
description: ${project.description}
version: ${project.version}
author: ${project.organization.name}
main: org.geysermc.floodgate.BungeePlugin

# Configuration for player linking
player-link:
  # Whether to enable the linking system. Turning this off will prevent
  # players from using the linking feature even if they are already linked.
  enable: false
  # The type of storage system you want to use
  # Currently implemented: SQLite
  type: sqlite
  # Whether to allow the use of /linkaccount and /unlinkaccount
  # You can also use allow specific people to use the commands using the
  # permissions floodgate.linkaccount and floodgate.unlinkaccount.
  # This is only for linking, already connected people will stay connected
  allow-linking: true
  # The amount of time until a link code expires in seconds
  link-code-timeout: 300